image: Visual Studio 2019
before_build:
  - choco install codecov
build_script:
  - dotnet build
test_script:
  - dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
  - codecov -f ./App.Tests/coverage.opencover.xml
